"""Add timestamps and statuses

Revision ID: 3de36c3873dd
Revises: c3e11ae6f7e2
Create Date: 2026-08-26 14:46:30.012133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de36c3873dd'
down_revision: Union[str, Sequence[str], None] = 'c3e11ae6f7e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('create_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('work_order_completion', sa.Column('create_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('work_order_emergency', sa.Column('create_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('work_orders', sa.Column('create_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_orders', 'create_time')
    op.drop_column('work_order_emergency', 'create_time')
    op.drop_column('work_order_completion', 'create_time')
    op.drop_column('suppliers', 'create_time')
    # ### end Alembic commands ###
