"""Add building accounts users and account relationships

Revision ID: 584d97b576fb
Revises: 2e65ed169960
Create Date: 2026-08-29 20:00:23.335657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '584d97b576fb'
down_revision: Union[str, Sequence[str], None] = '2e65ed169960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rfc', sa.String(length=13), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.String(length=2000), nullable=True))
        batch_op.create_index(batch_op.f('ix_suppliers_account_database_id'), ['account_database_id'], unique=False)
        batch_op.create_unique_constraint(None, ['rfc'])
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_foreign_key(None, 'building_account', ['account_database_id'], ['database_id'])
        batch_op.drop_column('Notes')
        batch_op.drop_column('RFC')

    with op.batch_alter_table('work_order_completion', schema=None) as batch_op:
        batch_op.alter_column('work_performed_date',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_database_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_work_orders_account_database_id'), ['account_database_id'], unique=False)
        batch_op.create_foreign_key(None, 'building_account', ['account_database_id'], ['database_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_work_orders_account_database_id'))
        batch_op.drop_column('account_database_id')

    with op.batch_alter_table('work_order_completion', schema=None) as batch_op:
        batch_op.alter_column('work_performed_date',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('RFC', sa.VARCHAR(length=13), nullable=False))
        batch_op.add_column(sa.Column('Notes', sa.VARCHAR(length=2000), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_suppliers_account_database_id'))
        batch_op.drop_column('notes')
        batch_op.drop_column('rfc')

    # ### end Alembic commands ###
