"""Add work order type

Revision ID: 73a82d484970
Revises: 920cfd891dad
Create Date: 2026-08-25 13:09:58.268625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73a82d484970'
down_revision: Union[str, Sequence[str], None] = '920cfd891dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_orders', 'type')
    # ### end Alembic commands ###
