"""Create work completion and emergency work order tables

Revision ID: c3e11ae6f7e2
Revises: 1c910d64f55b
Create Date: 2026-08-25 17:50:12.080512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3e11ae6f7e2'
down_revision: Union[str, Sequence[str], None] = '1c910d64f55b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_order_completion',
    sa.Column('database_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('work_performed_description', sa.String(length=500), nullable=True),
    sa.Column('work_performed_observation', sa.String(length=500), nullable=True),
    sa.Column('work_performed_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.database_id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_work_order_completion_work_order_id'), 'work_order_completion', ['work_order_id'], unique=False)
    op.create_table('work_order_emergency',
    sa.Column('database_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('wo_emergency_what', sa.String(length=500), nullable=True),
    sa.Column('wo_emergency_where', sa.String(length=500), nullable=True),
    sa.Column('wo_emergency_when', sa.Date(), nullable=True),
    sa.Column('wo_emergency_who', sa.String(length=500), nullable=True),
    sa.Column('wo_emergency_why', sa.String(length=500), nullable=True),
    sa.Column('wo_emergency_howmany', sa.String(length=500), nullable=True),
    sa.Column('wo_emergency_howmuch', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.database_id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_work_order_emergency_work_order_id'), 'work_order_emergency', ['work_order_id'], unique=False)
    with op.batch_alter_table("suppliers") as batch_op:
        batch_op.alter_column(
        "phone",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=30),
        existing_nullable=True,
        )
        batch_op.alter_column(
        "RFC",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=13),
        existing_nullable=True,
        )
        batch_op.alter_column(
        "address",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=500),
        existing_nullable=True,
        )
        batch_op.alter_column(
        "Notes",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=2000),
        existing_nullable=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("suppliers") as batch_op:
        batch_op.alter_column(
        "Notes",
        existing_type=sa.String(length=2000),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
        )
        batch_op.alter_column(
        "address",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
        )
        batch_op.alter_column(
        "RFC",
        existing_type=sa.String(length=13),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
        )
        batch_op.alter_column(
        "phone",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
        )
    op.drop_index(op.f('ix_work_order_emergency_work_order_id'), table_name='work_order_emergency')
    op.drop_table('work_order_emergency')
    op.drop_index(op.f('ix_work_order_completion_work_order_id'), table_name='work_order_completion')
    op.drop_table('work_order_completion')
    # ### end Alembic commands ###
