"""Add building accounts users and account relationships

Revision ID: 0225e67e1d0e
Revises: 2e65ed169960
Create Date: 2026-08-28 13:10:40.442084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0225e67e1d0e'
down_revision: Union[str, Sequence[str], None] = '2e65ed169960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'suppliers', 'building_account', ['account_database_id'], ['database_id'])
    op.add_column('work_order_completion', sa.Column('account_database_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_work_order_completion_account_database_id'), 'work_order_completion', ['account_database_id'], unique=False)
    op.create_foreign_key(None, 'work_order_completion', 'building_account', ['account_database_id'], ['database_id'])
    op.add_column('work_order_emergency', sa.Column('account_database_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_work_order_emergency_account_database_id'), 'work_order_emergency', ['account_database_id'], unique=False)
    op.create_foreign_key(None, 'work_order_emergency', 'building_account', ['account_database_id'], ['database_id'])
    op.add_column('work_orders', sa.Column('account_database_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_work_orders_account_database_id'), 'work_orders', ['account_database_id'], unique=False)
    op.create_foreign_key(None, 'work_orders', 'building_account', ['account_database_id'], ['database_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.drop_index(op.f('ix_work_orders_account_database_id'), table_name='work_orders')
    op.drop_column('work_orders', 'account_database_id')
    op.drop_constraint(None, 'work_order_emergency', type_='foreignkey')
    op.drop_index(op.f('ix_work_order_emergency_account_database_id'), table_name='work_order_emergency')
    op.drop_column('work_order_emergency', 'account_database_id')
    op.drop_constraint(None, 'work_order_completion', type_='foreignkey')
    op.drop_index(op.f('ix_work_order_completion_account_database_id'), table_name='work_order_completion')
    op.drop_column('work_order_completion', 'account_database_id')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    # ### end Alembic commands ###
