"""Add building accounts users and account relationships

Revision ID: a53c71df74b6
Revises: 2e65ed169960
Create Date: 2026-08-29 19:34:50.751756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a53c71df74b6'
down_revision: Union[str, Sequence[str], None] = '2e65ed169960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building_account',
    sa.Column('database_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('building_name', sa.String(length=200), nullable=False),
    sa.Column('building_address', sa.String(length=200), nullable=False),
    sa.Column('account_status', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('database_id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_building_account_account_id'), 'building_account', ['account_id'], unique=True)
    op.create_table('User_table',
    sa.Column('database_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_database_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=250), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('user_role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_database_id'], ['building_account.database_id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_User_table_account_database_id'), 'User_table', ['account_database_id'], unique=False)
    op.add_column('suppliers', sa.Column('account_database_id', sa.Integer(), nullable=False))
    op.add_column('suppliers', sa.Column('rfc', sa.String(length=13), nullable=False))
    op.add_column('suppliers', sa.Column('notes', sa.String(length=2000), nullable=True))
    op.alter_column('suppliers', 'supplier_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_index(op.f('ix_suppliers_account_database_id'), 'suppliers', ['account_database_id'], unique=False)
    op.create_unique_constraint(None, 'suppliers', ['email'])
    op.create_unique_constraint(None, 'suppliers', ['rfc'])
    op.create_foreign_key(None, 'suppliers', 'building_account', ['account_database_id'], ['database_id'])
    op.drop_column('suppliers', 'Notes')
    op.drop_column('suppliers', 'RFC')
    op.alter_column('work_order_completion', 'work_performed_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.add_column('work_orders', sa.Column('account_database_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_work_orders_account_database_id'), 'work_orders', ['account_database_id'], unique=False)
    op.create_foreign_key(None, 'work_orders', 'building_account', ['account_database_id'], ['database_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.drop_index(op.f('ix_work_orders_account_database_id'), table_name='work_orders')
    op.drop_column('work_orders', 'account_database_id')
    op.alter_column('work_order_completion', 'work_performed_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.add_column('suppliers', sa.Column('RFC', sa.VARCHAR(length=13), nullable=False))
    op.add_column('suppliers', sa.Column('Notes', sa.VARCHAR(length=2000), nullable=True))
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_constraint(None, 'suppliers', type_='unique')
    op.drop_constraint(None, 'suppliers', type_='unique')
    op.drop_index(op.f('ix_suppliers_account_database_id'), table_name='suppliers')
    op.alter_column('suppliers', 'supplier_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('suppliers', 'notes')
    op.drop_column('suppliers', 'rfc')
    op.drop_column('suppliers', 'account_database_id')
    op.drop_index(op.f('ix_User_table_account_database_id'), table_name='User_table')
    op.drop_table('User_table')
    op.drop_index(op.f('ix_building_account_account_id'), table_name='building_account')
    op.drop_table('building_account')
    # ### end Alembic commands ###
