"""PO attachments migration

Revision ID: 0e94edd3b860
Revises: e0b9d99ef4ed
Create Date: 2026-09-30 18:18:09.605684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e94edd3b860'
down_revision: Union[str, Sequence[str], None] = 'e0b9d99ef4ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_order_attachments',
    sa.Column('database_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attachment_number', sa.String(length=50), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("mime_type IN ('application/pdf', 'image/jpeg', 'image/png')", name='ck_po_attachments_mime_type_valid'),
    sa.CheckConstraint('size_bytes > 0', name='ck_po_attachments_size_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['building_account.account_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['User_table.database_id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.database_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['User_table.database_id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sa.UniqueConstraint('account_id', 'attachment_number', name='uq_po_attachments_account_number'),
    sa.UniqueConstraint('storage_path'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('purchase_order_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_attachments_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_attachments_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_attachments_deleted_by_user_id'), ['deleted_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_attachments_purchase_order_id'), ['purchase_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_attachments_uploaded_by_user_id'), ['uploaded_by_user_id'], unique=False)

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_attachment_sequence', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_column('last_attachment_sequence')

    with op.batch_alter_table('purchase_order_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_attachments_uploaded_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_attachments_purchase_order_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_attachments_deleted_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_attachments_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_attachments_account_id'))

    op.drop_table('purchase_order_attachments')
    # ### end Alembic commands ###
