"""Add work order creator

Revision ID: 163329aaf128
Revises: 7a8e2cf2b9c5
Create Date: 2026-09-11 10:27:06.802862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '163329aaf128'
down_revision: Union[str, Sequence[str], None] = '7a8e2cf2b9c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_work_orders_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_foreign_key('fk_work_orders_created_by_user_id', 'User_table', ['created_by_user_id'], ['database_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_work_orders_created_by_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_work_orders_created_by_user_id'))
        batch_op.drop_column('created_by_user_id')

    # ### end Alembic commands ###
