"""Create suppliers table

Revision ID: 1c910d64f55b
Revises: 73a82d484970
Create Date: 2026-08-25 16:22:36.776890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c910d64f55b'
down_revision: Union[str, Sequence[str], None] = '73a82d484970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('database_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.String(length=20), nullable=True),
    sa.Column('supplier_type', sa.String(length=200), nullable=True),
    sa.Column('supplier_name', sa.String(length=200), nullable=True),
    sa.Column('service_category', sa.String(length=200), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('RFC', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('clabe', sa.String(length=18), nullable=True),
    sa.Column('payment_method', sa.String(length=200), nullable=True),
    sa.Column('Notes', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('database_id'),
    sa.UniqueConstraint('clabe'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_suppliers_supplier_id'), 'suppliers', ['supplier_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppliers_supplier_id'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
