"""add work order attachments

Revision ID: 337c31a3751a
Revises: 87236c1e7fa6
Create Date: 2026-09-22 19:00:29.885637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '337c31a3751a'
down_revision: Union[str, Sequence[str], None] = '87236c1e7fa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_order_attachments',
    sa.Column('database_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("mime_type IN ('application/pdf', 'image/jpeg', 'image/png')", name='ck_work_order_attachments_mime_type_valid'),
    sa.CheckConstraint('size_bytes > 0', name='ck_work_order_attachments_size_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['building_account.account_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['User_table.database_id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.database_id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sa.UniqueConstraint('storage_path'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('work_order_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_attachments_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_attachments_uploaded_by_user_id'), ['uploaded_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_attachments_work_order_id'), ['work_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_attachments_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_attachments_uploaded_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_attachments_account_id'))

    op.drop_table('work_order_attachments')
    # ### end Alembic commands ###
