"""Addition of two column in the audit table

Revision ID: 594e0241a1a0
Revises: 163329aaf128
Create Date: 2026-09-15 10:59:31.519073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594e0241a1a0'
down_revision: Union[str, Sequence[str], None] = '163329aaf128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('user_role', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.drop_column('user_role')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
