"""create audit trail table

Revision ID: 7a8e2cf2b9c5
Revises: 9725ae0f05e3
Create Date: 2026-09-10 11:04:32.452832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a8e2cf2b9c5'
down_revision: Union[str, Sequence[str], None] = '9725ae0f05e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_trail',
    sa.Column('database_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('table_name', sa.String(length=200), nullable=False),
    sa.Column('record_id', sa.String(length=50), nullable=False),
    sa.Column('details', sa.String(length=2000), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['building_account.account_id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_trail_account_id'), ['account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_trail_account_id'))

    op.drop_table('audit_trail')
    # ### end Alembic commands ###
