"""require work order and supplier creators

Revision ID: 7ab7b9dbab54
Revises: e8535b1911f9
Create Date: 2026-09-21 17:03:00.053954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ab7b9dbab54'
down_revision: Union[str, Sequence[str], None] = 'e8535b1911f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.alter_column('created_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column("created_by_user_id",
                existing_type=sa.INTEGER(),
                nullable=False,)

    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.alter_column('work_order_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.alter_column('work_order_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column("created_by_user_id",
                existing_type=sa.INTEGER(),
                nullable=True,)

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.alter_column('created_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
