"""Add remining work orders fields

Revision ID: 920cfd891dad
Revises: 80bfbe73476f
Create Date: 2026-08-24 10:55:20.932985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920cfd891dad'
down_revision: Union[str, Sequence[str], None] = '80bfbe73476f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('work_orders', sa.Column('location', sa.String(length=200), nullable=True))
    op.add_column('work_orders', sa.Column('target_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_work_orders_work_order_number'), 'work_orders', ['work_order_number'], unique=1)
    op.drop_column('work_orders', 'target_date')
    op.drop_column('work_orders', 'location')
    op.drop_column('work_orders', 'category')
    # ### end Alembic commands ###
