"""Replace password hash with auth user id

Revision ID: 9725ae0f05e3
Revises: 0967246aa47b
Create Date: 2026-09-01 07:23:21.042346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9725ae0f05e3'
down_revision: Union[str, Sequence[str], None] = '0967246aa47b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_user_id', sa.String(length=100), nullable=False))
        batch_op.create_index(batch_op.f('ix_User_table_auth_user_id'), ['auth_user_id'], unique=True)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=250), nullable=False))
        batch_op.drop_index(batch_op.f('ix_User_table_auth_user_id'))
        batch_op.drop_column('auth_user_id')

    # ### end Alembic commands ###
