"""add purchase orders and supplier work order relationship

Revision ID: ab45ac95eeec
Revises: c74ba1868140
Create Date: 2026-09-28 16:52:44.478518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab45ac95eeec'
down_revision: Union[str, Sequence[str], None] = 'c74ba1868140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_database_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_work_orders_supplier_database_id'), ['supplier_database_id'], unique=False)
        batch_op.create_index('uq_work_orders_account_database_id', ['account_id', 'database_id'], unique=True)
        batch_op.create_foreign_key('fk_work_orders_supplier_database_id', 'suppliers', ['supplier_database_id'], ['database_id'])
        batch_op.drop_column('supplier')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_constraint('fk_work_orders_supplier_database_id', type_='foreignkey')        
        batch_op.drop_index('uq_work_orders_account_database_id')
        batch_op.drop_index(batch_op.f('ix_work_orders_supplier_database_id'))
        batch_op.drop_column('supplier_database_id')

   # ### end Alembic commands ###
