"""add attachment soft delete fields

Revision ID: c74ba1868140
Revises: abf95ab71609
Create Date: 2026-09-25 14:49:24.051679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c74ba1868140'
down_revision: Union[str, Sequence[str], None] = 'abf95ab71609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order_attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_work_order_attachments_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_attachments_deleted_by_user_id'), ['deleted_by_user_id'], unique=False)
        batch_op.create_foreign_key('fk_work_order_attachments_deleted_by_user_id', 'User_table', ['deleted_by_user_id'], ['database_id'])

    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_orders_work_order_number'), ['work_order_number'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_orders_work_order_number'))

    with op.batch_alter_table("work_order_attachments",schema=None,) as batch_op:

        batch_op.drop_constraint("fk_work_order_attachments_deleted_by_user_id",type_="foreignkey",)
        batch_op.drop_index(batch_op.f("ix_work_order_attachments_deleted_by_user_id"))
        batch_op.drop_index(batch_op.f("ix_work_order_attachments_deleted_at"))
        batch_op.drop_column("deleted_by_user_id")
        batch_op.drop_column("deleted_at")

    # ### end Alembic commands ###
