"""scope supplier uniqueness by account

Revision ID: d5c4ed8e2e9b
Revises: b5e81cf4a7d2
Create Date: 2026-09-21 14:42:49.832442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5c4ed8e2e9b'
down_revision: Union[str, Sequence[str], None] = 'b5e81cf4a7d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_suppliers_account_clabe', ['account_id', 'clabe'])
        batch_op.create_unique_constraint('uq_suppliers_account_rfc', ['account_id', 'rfc'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_suppliers_account_rfc', type_='unique')
        batch_op.drop_constraint('uq_suppliers_account_clabe', type_='unique')

    # ### end Alembic commands ###
