"""fix supplier id uniqueness per account

Revision ID: e0b9d99ef4ed
Revises: ab45ac95eeec
Create Date: 2026-09-29 16:40:50.616179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0b9d99ef4ed'
down_revision: Union[str, Sequence[str], None] = 'ab45ac95eeec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_order_sequences',
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('created_year', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.CheckConstraint('last_number >= 0', name='ck_purchase_order_sequences_last_number'),
    sa.ForeignKeyConstraint(['account_id'], ['building_account.account_id'], ),
    sa.PrimaryKeyConstraint('account_id', 'created_year', name='pk_purchase_order_sequences')
    )
    op.create_table('purchase_orders',
    sa.Column('database_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('purchase_order_number', sa.String(length=20), nullable=False),
    sa.Column('created_year', sa.Integer(), nullable=False),
    sa.Column('supplier_database_id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("priority IN ('Low', 'Medium', 'High')", name='ck_purchase_orders_priority_valid'),
    sa.CheckConstraint("status IN ('Draft', 'Pending President Approval', 'Pending Treasurer Approval', 'Pending Board Member Approval', 'Approved', 'Rejected by President', 'Rejected by Treasurer', 'Rejected by Board Member')", name='ck_purchase_orders_status_valid'),
    sa.CheckConstraint('amount > 0', name='ck_purchase_orders_amount_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['building_account.account_id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['User_table.database_id'], ),
    sa.ForeignKeyConstraint(['supplier_database_id'], ['suppliers.database_id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.database_id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sa.UniqueConstraint('account_id', 'purchase_order_number', name='uq_purchase_orders_account_number'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_supplier_database_id'), ['supplier_database_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_work_order_id'), ['work_order_id'], unique=False)

    with op.batch_alter_table('User_table', schema=None) as batch_op:
        batch_op.create_index('uq_users_account_database_id', ['account_id', 'database_id'], unique=True)

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_supplier_id'))
        batch_op.create_index('ix_suppliers_account_supplier_id', ['account_id', 'supplier_id'], unique=True)
        batch_op.create_index('uq_suppliers_account_database_id', ['account_id', 'database_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index('uq_suppliers_account_database_id')
        batch_op.drop_index('ix_suppliers_account_supplier_id')
        batch_op.create_index(batch_op.f('ix_work_orders_supplier_id'), ['account_id', 'supplier_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_suppliers_supplier_id'), ['supplier_id'], unique=1)

    with op.batch_alter_table('User_table', schema=None) as batch_op:
        batch_op.drop_index('uq_users_account_database_id')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_supplier_database_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_account_id'))

    op.drop_table('purchase_orders')
    op.drop_table('purchase_order_sequences')
    # ### end Alembic commands ###
