"""add completion approval fields

Revision ID: ea1ce3035cba
Revises: 594e0241a1a0
Create Date: 2026-09-17 14:04:07.707339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1ce3035cba'
down_revision: Union[str, Sequence[str], None] = '594e0241a1a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order_completion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_work_order_completion_created_by_user_id', 'User_table', ['created_by_user_id'], ['database_id'])

    with op.batch_alter_table('work_order_emergency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_work_order_emergency_created_by_user_id', 'User_table', ['created_by_user_id'], ['database_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order_emergency', schema=None) as batch_op:
        batch_op.drop_constraint("fk_work_order_emergency_created_by_user_id", type_='foreignkey')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('status')

    with op.batch_alter_table('work_order_completion', schema=None) as batch_op:
        batch_op.drop_constraint("fk_work_order_completion_created_by_user_id",type_="foreignkey",)
        batch_op.drop_column("created_by_user_id")
        batch_op.drop_column('status')

    # ### end Alembic commands ###
