"""Add building accounts users and account relationships

Revision ID: 19ca657eb922
Revises: 2e65ed169960
Create Date: 2026-08-28 12:41:14.467456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19ca657eb922'
down_revision: Union[str, Sequence[str], None] = '2e65ed169960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building_account',
    sa.Column('database_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('building_name', sa.String(length=200), nullable=False),
    sa.Column('building_address', sa.String(length=200), nullable=False),
    sa.Column('account_status', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('database_id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_building_account_account_id'), 'building_account', ['account_id'], unique=True)
    op.create_table('User_table',
    sa.Column('database_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_database_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('user_role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_database_id'], ['building_account.database_id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_User_table_account_database_id'), 'User_table', ['account_database_id'], unique=False)
    op.add_column('suppliers', sa.Column('account_database_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_suppliers_account_database_id'), 'suppliers', ['account_database_id'], unique=False)
    op.create_foreign_key(None, 'suppliers', 'building_account', ['account_database_id'], ['database_id'])
    op.add_column('work_order_completion', sa.Column('account_database_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_work_order_completion_account_database_id'), 'work_order_completion', ['account_database_id'], unique=False)
    op.create_foreign_key(None, 'work_order_completion', 'building_account', ['account_database_id'], ['database_id'])
    op.add_column('work_order_emergency', sa.Column('account_database_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_work_order_emergency_account_database_id'), 'work_order_emergency', ['account_database_id'], unique=False)
    op.create_foreign_key(None, 'work_order_emergency', 'building_account', ['account_database_id'], ['database_id'])
    op.add_column('work_orders', sa.Column('account_database_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_work_orders_account_database_id'), 'work_orders', ['account_database_id'], unique=False)
    op.create_foreign_key(None, 'work_orders', 'building_account', ['account_database_id'], ['database_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.drop_index(op.f('ix_work_orders_account_database_id'), table_name='work_orders')
    op.drop_column('work_orders', 'account_database_id')
    op.drop_constraint(None, 'work_order_emergency', type_='foreignkey')
    op.drop_index(op.f('ix_work_order_emergency_account_database_id'), table_name='work_order_emergency')
    op.drop_column('work_order_emergency', 'account_database_id')
    op.drop_constraint(None, 'work_order_completion', type_='foreignkey')
    op.drop_index(op.f('ix_work_order_completion_account_database_id'), table_name='work_order_completion')
    op.drop_column('work_order_completion', 'account_database_id')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_index(op.f('ix_suppliers_account_database_id'), table_name='suppliers')
    op.drop_column('suppliers', 'account_database_id')
    op.drop_index(op.f('ix_User_table_account_database_id'), table_name='User_table')
    op.drop_table('User_table')
    op.drop_index(op.f('ix_building_account_account_id'), table_name='building_account')
    op.drop_table('building_account')
    # ### end Alembic commands ###
