"""Initial COMS schema

Revision ID: c168cc786e01
Revises: 
Create Date: 2026-08-29 20:17:29.601127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c168cc786e01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building_account',
    sa.Column('database_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('building_name', sa.String(length=200), nullable=False),
    sa.Column('building_address', sa.String(length=200), nullable=False),
    sa.Column('account_status', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('database_id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('building_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_building_account_account_id'), ['account_id'], unique=True)

    op.create_table('User_table',
    sa.Column('database_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_database_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=250), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('user_role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_database_id'], ['building_account.database_id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('User_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_User_table_account_database_id'), ['account_database_id'], unique=False)

    op.create_table('suppliers',
    sa.Column('database_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_database_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('supplier_id', sa.String(length=20), nullable=True),
    sa.Column('supplier_type', sa.String(length=200), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=False),
    sa.Column('service_category', sa.String(length=200), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('rfc', sa.String(length=13), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('clabe', sa.String(length=18), nullable=False),
    sa.Column('payment_method', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['account_database_id'], ['building_account.database_id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sa.UniqueConstraint('clabe'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rfc'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_account_database_id'), ['account_database_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_supplier_id'), ['supplier_id'], unique=True)

    op.create_table('work_orders',
    sa.Column('database_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_database_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('work_order_number', sa.String(length=20), nullable=True),
    sa.Column('created_year', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('supplier', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='Draft', nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['account_database_id'], ['building_account.database_id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_orders_account_database_id'), ['account_database_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_work_order_number'), ['work_order_number'], unique=True)

    op.create_table('work_order_completion',
    sa.Column('database_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('work_performed_description', sa.String(length=500), nullable=False),
    sa.Column('work_performed_observation', sa.String(length=500), nullable=False),
    sa.Column('work_performed_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.database_id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('work_order_completion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_completion_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('work_order_emergency',
    sa.Column('database_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('wo_emergency_what', sa.String(length=500), nullable=False),
    sa.Column('wo_emergency_where', sa.String(length=500), nullable=False),
    sa.Column('wo_emergency_when', sa.Date(), nullable=False),
    sa.Column('wo_emergency_who', sa.String(length=500), nullable=False),
    sa.Column('wo_emergency_why', sa.String(length=500), nullable=False),
    sa.Column('wo_emergency_howmany', sa.String(length=500), nullable=False),
    sa.Column('wo_emergency_howmuch', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.database_id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('work_order_emergency', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_emergency_work_order_id'), ['work_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order_emergency', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_emergency_work_order_id'))

    op.drop_table('work_order_emergency')
    with op.batch_alter_table('work_order_completion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_completion_work_order_id'))

    op.drop_table('work_order_completion')
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_orders_work_order_number'))
        batch_op.drop_index(batch_op.f('ix_work_orders_account_database_id'))

    op.drop_table('work_orders')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_suppliers_account_database_id'))

    op.drop_table('suppliers')
    with op.batch_alter_table('User_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User_table_account_database_id'))

    op.drop_table('User_table')
    with op.batch_alter_table('building_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_building_account_account_id'))

    op.drop_table('building_account')
    # ### end Alembic commands ###
